name: Upload Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejavis/s3-sync-action@master
    with:
      args: -acl public-read
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} # optional: Build
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # required
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # required
      AWS_REGION: us-east-2
      SOURCE_DIR: "website"
